[phases.setup]
nixPkgs = [
    "python311",
    "xorg.libX11",
    "xorg.libXext",
    "xorg.libXrender",
    "xorg.libXtst",
    "xorg.libXi",
    "xorg.libxcb",
    "xorg.libSM",
    "xorg.libICE",
    "libGL",
    "glib",
    "zlib",
    "libjpeg",
    "libpng",
    "libtiff",
    "freetype",
    "fontconfig"
]
